"""Phase 1: Core Zero-Knowledge Vault schema

Revision ID: 06a2ba1038d3
Revises: 
Create Date: 2026-09-03 00:14:18.170929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '06a2ba1038d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_id'), 'audit_event', ['id'], unique=False)
    op.create_index(op.f('ix_audit_event_vault_id'), 'audit_event', ['vault_id'], unique=False)
    op.create_table('beneficiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('share_index', sa.Integer(), nullable=True),
    sa.Column('invitation_hash', sa.Text(), nullable=True),
    sa.Column('invitation_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiary_id'), 'beneficiary', ['id'], unique=False)
    op.create_index(op.f('ix_beneficiary_vault_id'), 'beneficiary', ['vault_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_beneficiary_id'), 'notification_log', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_notification_log_id'), 'notification_log', ['id'], unique=False)
    op.create_index(op.f('ix_notification_log_vault_id'), 'notification_log', ['vault_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_family_id'), 'refresh_token', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_id'), 'refresh_token', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('wrapped_vmk', sa.Text(), nullable=True),
    sa.Column('vmk_crypto_version', sa.Integer(), nullable=True),
    sa.Column('vmk_kdf_algorithm', sa.String(length=50), nullable=True),
    sa.Column('vmk_kdf_salt', sa.Text(), nullable=True),
    sa.Column('vmk_kdf_parameters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_id'), 'vault', ['id'], unique=False)
    op.create_index(op.f('ix_vault_user_id'), 'vault', ['user_id'], unique=False)
    op.create_table('vault_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('wrapped_mek', sa.Text(), nullable=False),
    sa.Column('crypto_version', sa.Integer(), nullable=False),
    sa.Column('crypto_metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_message_id'), 'vault_message', ['id'], unique=False)
    op.create_index(op.f('ix_vault_message_vault_id'), 'vault_message', ['vault_id'], unique=False)
    op.create_table('vault_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('grace_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_reason', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_status_id'), 'vault_status', ['id'], unique=False)
    op.create_index(op.f('ix_vault_status_vault_id'), 'vault_status', ['vault_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_status_vault_id'), table_name='vault_status')
    op.drop_index(op.f('ix_vault_status_id'), table_name='vault_status')
    op.drop_table('vault_status')
    op.drop_index(op.f('ix_vault_message_vault_id'), table_name='vault_message')
    op.drop_index(op.f('ix_vault_message_id'), table_name='vault_message')
    op.drop_table('vault_message')
    op.drop_index(op.f('ix_vault_user_id'), table_name='vault')
    op.drop_index(op.f('ix_vault_id'), table_name='vault')
    op.drop_table('vault')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_family_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_notification_log_vault_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_beneficiary_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_beneficiary_vault_id'), table_name='beneficiary')
    op.drop_index(op.f('ix_beneficiary_id'), table_name='beneficiary')
    op.drop_table('beneficiary')
    op.drop_index(op.f('ix_audit_event_vault_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_id'), table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###