"""phase_2_access_requests_and_beneficiary_updates

Revision ID: e0bbcaab9d2c
Revises: 06a2ba1038d3
Create Date: 2026-09-05 05:18:42.604381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e0bbcaab9d2c'
down_revision: Union[str, None] = '06a2ba1038d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: heartbeat_config table already exists in some environments (created by Phase 1 models)
    # Only create access_request table and add new columns to existing tables
    op.create_table('access_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_request_beneficiary_id'), 'access_request', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_access_request_id'), 'access_request', ['id'], unique=False)
    op.create_index(op.f('ix_access_request_vault_id'), 'access_request', ['vault_id'], unique=False)
    op.create_foreign_key(None, 'audit_event', 'vault', ['vault_id'], ['id'])
    op.add_column('beneficiary', sa.Column('share_data', sa.Text(), nullable=True))
    op.add_column('beneficiary', sa.Column('invitation_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('beneficiary', sa.Column('invitation_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'beneficiary', 'vault', ['vault_id'], ['id'])
    op.add_column('notification_log', sa.Column('type', sa.String(length=30), nullable=False))
    op.create_foreign_key(None, 'notification_log', 'vault', ['vault_id'], ['id'])
    op.create_foreign_key(None, 'notification_log', 'beneficiary', ['beneficiary_id'], ['id'])
    op.drop_column('notification_log', 'event_type')
    op.create_foreign_key(None, 'refresh_token', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'vault', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'vault_message', 'vault', ['vault_id'], ['id'])
    op.alter_column('vault_status', 'vault_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'vault_status', 'vault', ['vault_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vault_status', type_='foreignkey')
    op.alter_column('vault_status', 'vault_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'vault_message', type_='foreignkey')
    op.drop_constraint(None, 'vault', type_='foreignkey')
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.add_column('notification_log', sa.Column('event_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notification_log', type_='foreignkey')
    op.drop_constraint(None, 'notification_log', type_='foreignkey')
    op.drop_column('notification_log', 'type')
    op.drop_constraint(None, 'beneficiary', type_='foreignkey')
    op.drop_column('beneficiary', 'invitation_accepted_at')
    op.drop_column('beneficiary', 'invitation_sent_at')
    op.drop_column('beneficiary', 'share_data')
    op.drop_constraint(None, 'audit_event', type_='foreignkey')
    op.drop_index(op.f('ix_access_request_vault_id'), table_name='access_request')
    op.drop_index(op.f('ix_access_request_id'), table_name='access_request')
    op.drop_index(op.f('ix_access_request_beneficiary_id'), table_name='access_request')
    op.drop_table('access_request')
    # Note: heartbeat_config table is not dropped as it may be used by other revisions
    # ### end Alembic commands ###